### ISSUE TITLE
Project name is clunky & misleading

### ISSUE THREAD

**Issue by Splizard** [liquidata-inc/go-mysql-server#160]
go-mysql-server is a bit of a clunky name and import path, when I first saw the project appear in Go news feeds I thought it was another mysql driver.

However this is a really cool project! A Go SQL engine for testing, data interfaces etc

Perhaps a name-change could reflect this?

ie
* mysqlingo
* sqlingo
* sqle
* liquidsql

**Comment by zachmu** [comment]
Hmm, interesting idea!

We'll shop this around the team.

**Comment by zachmu** [comment]
Thanks for the suggestion, but after discussion with the team we've decided to keep the name as is and work on improving our docs to make the purpose of the project clearer.
