### ISSUE TITLE
Support UTC_TIMESTAMP()

### ISSUE THREAD

**Issue by tooolbox** [liquidata-inc/go-mysql-server#167]
Looking at using this project for unit-testing purposes; very nice to have an in-memory Mysql database!

It's good to have `NOW()` support but I do need `UTC_TIMESTAMP()` as well.  Is this something on the agenda soon, or should I dive in and figure out a PR?

Thanks 👍

**Comment by zachmu** [comment]
Hi @tooolbox ,

We don't have any immediate plans to implement UTC_TIMESTAMP, but dive in! It is pretty simple to add new functions. Start with this file:

https://github.com/liquidata-inc/go-mysql-server/blob/master/sql/expression/function/registry.go

Let us know if you have any questions!

**Comment by tooolbox** [comment]
Great, thanks for the info.  I turned out to not need this right this split instant, so I'm going to close this so the issue doesn't hang around, but I know what to do now once the time arises.

**Comment by zachmu** [comment]
Dustin is going to tackle this today

**Comment by zachmu** [comment]
This is now in master. Let us know if you find any issues.
