### ISSUE TITLE
Vitess Dep

### ISSUE THREAD

**Issue by tooolbox** [liquidata-inc/go-mysql-server#175]
Per the readme:

> go-mysql-server relies on a fork of vitess, which implements the SQL parsing and SQL server for the engine. To use this fork of vitess, you must include the same replace directive in your project's go.mod file as this package does (see the go.mod file for the exact line to copy and paste):

> replace vitess.io/vitess => github.com/liquidata-inc/vitess v0.0.0-20200430040751-192bb76ecd8b

However, when I look at the `go.mod` file on master, there's no replace directive.  Is this documentation outdated?

**Comment by zachmu** [comment]
Yes, it is. Thanks for noticing! Fixing now.
