### ISSUE TITLE
. and ./auth fail tests when not on windows

### ISSUE THREAD

**Issue by frioux** [liquidata-inc/go-mysql-server#96]
I suspect this is why:

```
auth/audit_test.go:// +build !windows
auth/common_test.go:// +build !windows
auth/native_test.go:// +build !windows
auth/none_test.go:// +build !windows
engine_pilosa_test.go:// +build !windows
```

The failure mode is some kind of deadlock or something?  It just sits forever

**Comment by zachmu** [comment]
Not sure what's going on here. I think those tests are disabled on windows because of a pilosa 
 dependency (pilosa doesn't build on windows), but it should be possible to separate those concerns. It will take me a while to dig into this, so let me know if this is blocking you.

**Comment by frioux** [comment]
Not blocking at all, was just running `go test ./...` before any other stuff :)

**Comment by zachmu** [comment]
This is fixed in the latest commit. All tests should pass on Linux now. Let us know if you find any other issues.
