### ISSUE TITLE
test suggestions?

### ISSUE THREAD

**Issue by frioux** [liquidata-inc/go-mysql-server#97]
I'd like to use this for tests (like I did with the src-d version before it was abandoned.)  One of the things I could never figure out how to do with `go-mysql-server` was various kinds of error injection.  For example, I'd like to be able to do weird stuff like if someone searches by a specific id I insert a sleep to test my timeout code.  For another id I'd like to be able to surface some weird error, so I can make sure my mysql error handling works.  Any ideas on how to do this?  I couldn't figure it out from the docs, but maybe I missed something.

**Comment by zachmu** [comment]
If you're running this in a server context, I think where you want to look first is handler.go:

https://github.com/liquidata-inc/go-mysql-server/blob/master/server/handler.go

It should be relatively straightforward to implement a wrapper for this type that intercepts queries, examines them, and does some special logic before dispatching to the base type. That's how I would start.

Does that help?

**Comment by frioux** [comment]
Hoping to try this out tomorrow; thanks for your quick response, will update here with any progress and maybe an example that you could put in docs if you want.

**Comment by frioux** [comment]
(Gotta resolve at least #104 to be able to run tests.)

**Comment by zachmu** [comment]
Going to close this since it's so old. Let us know if you have a contribution for error injection like you mentioned.
